MACHINE ?= "raspberrypi5"

BOOT_SPACE = "51200"

PREFERRED_VERSION_linux-raspberrypi = "6.6.%"
DISTRO_FEATURES:remove = "x11 wayland"
ENABLE_UART = "1"

LICENSE_FLAGS_ACCEPTED = "synaptics-killswitch"
IMAGE_FSTYPES:append = " rpi-sdimg"

